name: CI

on:
  push:
    branches: [ main, master, feature/* ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: Lint / Typecheck / Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f backend/requirements.txt ]; then pip install -r backend/requirements.txt; fi
          pip install ruff mypy pytest

      - name: Ruff lint
        run: |
          ruff check backend

      - name: Mypy type check
        run: |
          mypy backend

      - name: Run tests
        run: |
          pytest backend/tests -q
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r backend/requirements.txt

      - name: Run tests
        run: |
          python -m pytest backend/tests -q
      - name: Install dev tools (ruff, mypy)
        run: |
          python -m pip install ruff mypy

      - name: Run ruff
        run: |
          python -m ruff check .

      - name: Run mypy
        run: |
          python -m mypy backend --ignore-missing-imports
